### PR TITLE
Julia07

### PR DESCRIPTION
**Pull request by dpo**
needs https://github.com/JuliaSmoothOptimizers/NLPModels.jl/pull/133

### CODE REVIEW

**Comment by dpo** [comment]
@abelsiqueira Bad news. This is failing on Linux with Julia 0.7.

**Comment by abelsiqueira** [comment]
I've tried recreating the previous passing pull request with no luck.

I tried putting the failing `ccall` inside a [loop](https://github.com/abelsiqueira/AmplNLReader.jl/blob/46dc36aad28aefb812d86d2059cd3d5e69a50745/src/ampl_model.jl#L312). When the `ccall` returns an absurd value, I hoped that a second call would fix it, but it doesn't, like [this](https://travis-ci.org/abelsiqueira/AmplNLReader.jl/jobs/433250026#L786).

The second error happens when the `rows` and `cols` are in the correct range, but the values are repeated, such as [this](https://travis-ci.org/abelsiqueira/AmplNLReader.jl/jobs/433251717#L953).

No ideas for now.

**Comment by dpo** [comment]
We should determine whether the problem comes from Julia or from the ASL itself. For that, it's necessary to write a C driver. I've done that before but I have no time to look into it now.

Do you see the issue locally with 0.7?

**Comment by abelsiqueira** [comment]
I see it locally after I wrote the loop.

I'm gonna have to keep this hanging for a while also.

**Comment by dpo** [comment]
Dropping Linux support until we can resolve this.

**Comment by dpo** [comment]
Now Coveralls fails because of https://github.com/JuliaCI/Coverage.jl/issues/175.

**Comment by dpo** [comment]
@abelsiqueira Any idea about this: https://travis-ci.org/JuliaSmoothOptimizers/AmplNLReader.jl/jobs/435075674#L172?

**Comment by abelsiqueira** [comment]
Looks like https://discourse.julialang.org/t/package-compatibility-caps/15301
We also haven't released a NLPModels version compatible with 1.0 yet.

**Comment by abelsiqueira** [comment]
Now releasing: https://github.com/JuliaLang/METADATA.jl/pull/18614

**Comment by dpo** [comment]
Haven't seen this green in a while.

**Pull request merged**
