### PR TITLE
Merge develop into master

### PR DESCRIPTION
**Pull request by dpo**

### CODE REVIEW

**Comment by abelsiqueira** [comment]
:100:

**Comment by dpo** [comment]
Something'up with the Travis badges; they're red but the builds passed.

**Comment by abelsiqueira** [comment]
I think there is some option preventing the build: https://travis-ci.org/JuliaSmoothOptimizers/AmplNLReader.jl/requests

**Comment by dpo** [comment]
I disabled "build branches" earlier on Travis to prevent duplicating the builds in PRs but it also had this side effect.

**Pull request merged**
