### PR TITLE
#49 + #48 = 

### PR DESCRIPTION
**Pull request by abelsiqueira**

### CODE REVIEW

**Comment by dpo** [comment]
Thanks! You can patch the ampl/mp source code directly in `deps/build.jl`.

**Comment by dpo** [comment]
```
Checking problem hs6ERROR: LoadError: LoadError: AmplNLReader.AmplException("Error while evaluating constraints Jacobian")
Stacktrace:
 [1] jac_coord(::AmplNLReader.AmplModel, ::Array{Float64,1}) at /home/travis/.julia/v0.6/AmplNLReader/src/ampl_model.jl:314
 [2] jac(::AmplNLReader.AmplModel, ::Array{Float64,1}) at /home/travis/.julia/v0.6/AmplNLReader/src/ampl_model.jl:322
 [3] copy!(::Array{Any,1}, ::Base.Generator{Array{NLPModels.AbstractNLPModel,1},##11#26}) at ./abstractarray.jl:573
 [4] #consistent_functions#2(::Int64, ::Float64, ::Array{Any,1}, ::Function, ::Array{NLPModels.AbstractNLPModel,1}) at /home/travis/.julia/v0.6/NLPModels/test/consistency.jl:180
 [5] (::#kw##consistent_functions)(::Array{Any,1}, ::#consistent_functions, ::Array{NLPModels.AbstractNLPModel,1}) at ./<missing>:0
 [6] #consistent_nlps#33(::Int64, ::Float64, ::Function, ::Array{NLPModels.AbstractNLPModel,1}) at /home/travis/.julia/v0.6/NLPModels/test/consistency.jl:282
 [7] macro expansion at /home/travis/.julia/v0.6/AmplNLReader/test/consistency.jl:18 [inlined]
 [8] anonymous at ./<missing>:?
 [9] include_from_node1(::String) at ./loading.jl:576
 [10] include(::String) at ./sysimg.jl:14
 [11] include_from_node1(::String) at ./loading.jl:576
 [12] include(::String) at ./sysimg.jl:14
 [13] process_options(::Base.JLOptions) at ./client.jl:305
 [14] _start() at ./client.jl:371
while loading /home/travis/.julia/v0.6/AmplNLReader/test/consistency.jl, in expression starting on line 8
while loading /home/travis/.julia/v0.6/AmplNLReader/test/runtests.jl, in expression starting on line 2
```
The problem seems to be in `jac_coord` (not in `jtprod` as I said previously). In #49, the issue occurred on `rosenbr`, but here it occurs on `hs6` (which has constraints).

**Comment by dpo** [comment]
Maybe try to reevaluate `nnzj` inside `jac_coord()`?

**Comment by abelsiqueira** [comment]
I gor `err = Int32[-353553104]`. Does it mean something special?

**Comment by dpo** [comment]
No, it looks like the wrong Int type is used somewhere. I get a different error now: https://travis-ci.org/JuliaSmoothOptimizers/AmplNLReader.jl/jobs/427368925#L4213.

There may be some mixup between `int`, `int64_t`, `size_t` and `ssize_t` variables between the Julia and C interfaces. I'll try to have a look.

**Comment by dpo** [comment]
I was finally able to build ampl/mp on a Linux machine and I'm able to reproduce the issue. That should help me investigate.

**Comment by dpo** [comment]
Oh well, they all fail! That's odd. We should completely deprecate AmplNLReader for Julia versions before 0.7 then. What do you think?!

**Comment by abelsiqueira** [comment]
> only support macOS on Julia 0.6.

SOunds good to me. Updating.

**Comment by abelsiqueira** [comment]
Now passing and ready to merge.

**Comment by dpo** [comment]
Excellent, thank you! Now we need a new release before we release the new NLPModels?!

**Comment by abelsiqueira** [comment]
Yes, created here: https://github.com/JuliaLang/METADATA.jl/pull/18099

**Pull request merged**
