### PR TITLE
Bump julia min

### PR DESCRIPTION
**Pull request by dpo**

### CODE REVIEW

**Comment by abelsiqueira** [comment]
This is not failing locally.

**Comment by dpo** [comment]
I fixed a few things that get rid of the evaluation errors (at least on the Linux box I have access to). Another error cropped up, having to do with row indices being out of bounds in a Jacobian or sparse constraint gradient evaluation. Let's see if it also comes up on TravisCI.

**Comment by dpo** [comment]
Another attempt with a patched C interface to eliminate `int64_t`. Locally, problems occur when calling `consistent_nlps` in the tests. Calls to `jac` return garbage in the `rows` and/or `cols` arrays. But I can never reproduce the issue when I call `jac` by hand. So I wonder if something is going on with `consistent_nlps`?!

**Comment by dpo** [comment]
I'm out of ideas. @abelsiqueira and @Xx-fractale-xX, would you mind seeing if this fails for you locally? It fails on one Linux machine at the university but I don't know why.

**Comment by abelsiqueira** [comment]
I'll try to test it today later, possibly tomorrow.

**Comment by abelsiqueira** [comment]
Locally it still passed. I had no luck on reproducing locally or fixing travis, so after checking some issues on Julia, I found https://github.com/JuliaLang/julia/pull/28251, which is related to memory corruption.  The PR is over my head, unfortunately, and I don't know for sure if this is the problem, however, the strange integer values suggests memory corruption.
The PR was added on 0.7, so I tried making `AmplNLReader` 0.7 compatible, and it appears to have passed: https://travis-ci.org/JuliaSmoothOptimizers/AmplNLReader.jl/builds/429334943

What do you think?

**Comment by dpo** [comment]
That's progress. I also learned the other day that Julia 1.0.1 fixed some memory corruption issues, so it would be good to get this going with 1.0 soon. At any rate, it's great that you got it working with 0.7. In the past few days I noticed that the crashes were somewhat random. Would you mind restarting the build a few times to see if it succeeds consistently?

**Comment by abelsiqueira** [comment]
Sure, I'll restart a few times.

We could drop a few 0.6 checks and after dropping 0.6 support, get the tests back. `AmplNLReader` is blocking `NLPModels 0.5.0`, so there is some back and forth before Julia 1.0.

**Comment by Xx-fractale-xX** [comment]
Tests passed on my laptop with `ubuntu 16.04`  and `julia 0.6.4`.

**Comment by dpo** [comment]
If this passes consistently with Julia 0.7, I propose we simply drop Julia 0.6. We should make one last release that supports 0.6 but isn't official (say v0.2.1). Users who wish to use Julia 0.6 can download release 0.2.1 and hope it doesn't crash. The next release (say v0.3.0) will only support 0.7+. Does that sound good?

**Comment by abelsiqueira** [comment]
Sounds good to me. Should we use this branch?

**Comment by dpo** [comment]
OK I can confirm that the tests pass for me on the linux box where 0.6 fails. I had to deactivate everything related to MPB (Ipopt doesn't build anyways). Should we remove all the JuMP/MPB-related stuff for the new release?

**Comment by abelsiqueira** [comment]
For the 0.7 release yes, but for 0.6 we just need to limit it to not use NLPModels 0.5.0, i.e. #49.

**Comment by dpo** [comment]
@abelsiqueira Feel free to clean up your PR if you have the time today.

**Comment by dpo** [comment]
I have a feeling the issue isn't related to NLPModels but to Julia itself. As #49 shows, bounding NLPModels still fails on Linux.

**Comment by abelsiqueira** [comment]
That's true, but for those that install locally, NLPModels 0.5.0 will break the current AmplNLReader.

**Comment by dpo** [comment]
Do you mean it will break because the MPB stuff was moved out?

**Comment by abelsiqueira** [comment]
Yes. NLPModels 0.5.0 will still handle Julia 0.6, though without JuMP/MPB. So if someone `Pkg.update()`, it will download NLPModels 0.5.0 and break AmplNLReader.

**Comment by dpo** [comment]
Yes I agree. So what are the next steps?

**Comment by abelsiqueira** [comment]
Having an AmplNLReader release limiting NLPModels 0.5.0 should help merging NLPModels 0.5.0 on Metadata, then it is
- NLPJuMPModels release;
- CUTEst release using NLPModels 0.5.0;
- NLPModels 0.6.0 dropping julia 0.6;
- AmplNLReader and CUTEst using NLPModels 0.6.0 dropping julia 0.6.

**Comment by dpo** [comment]
Perhaps we also need to upper bound Julia in AmplNLReader. I presume that when we say "0.6", it's really using "0.6.4". It didn't use to break with earlier versions, but I'm not sure when the break occurred. Perhaps we could limit to "0.6.3", "0.6.2", etc., and see when TravisCI succeeds?

**Comment by abelsiqueira** [comment]
Makes sense. Let me try.

**Pull request closed without merging**
