### PR TITLE
MPB interface

### PR DESCRIPTION
**Pull request by dpo**
See https://github.com/JuliaSmoothOptimizers/NLPModels.jl/pull/45.

### CODE REVIEW

**Comment by dpo** [comment]
@abelsiqueira There's an error related to dercheck here:
https://travis-ci.org/JuliaSmoothOptimizers/AmplNLReader.jl/jobs/162583424#L1222

**Comment by abelsiqueira** [comment]
That's the `obj` before `hessian` problem. Since Ampl was out of the tests, I removed it.
How about I add a flag in `consistent_nlps` for `check_derivative`, then in Ampl you set to false?

**Comment by dpo** [comment]
I'm thinking we could either override `dercheck` for `AmplModels` so that `obj` is always called before `hess`, or we could have a `safe` option when creating an `AmplModel` that activates the same behavior. That issue comes up regularly.

**Comment by abelsiqueira** [comment]
That's a pure Ampl problem? Is it a problem? How do they deal with it?
I think a safe option is best.

**Comment by dpo** [comment]
Yes it's specific to AMPL and has caused me headaches in the past. I'll add a "safe" option to `AmplModel`s.

**Comment by dpo** [comment]
That didn't do it:
https://travis-ci.org/JuliaSmoothOptimizers/AmplNLReader.jl/jobs/162877702#L1164

Any idea what's wrong?

**Comment by dpo** [comment]
Got it. Rebase problem.

**Comment by abelsiqueira** [comment]
Thank you

**Pull request merged**
