### PR TITLE
fix path to problems in consistency test

### PR DESCRIPTION
**Pull request by dpo**

### CODE REVIEW

**Comment by abelsiqueira** [comment]
This will need a new NLPModels release. I'm preparing a PR with https://github.com/JuliaSmoothOptimizers/NLPModels.jl/issues/92, though we can could release a new version right away.

**Comment by dpo** [comment]
No hurry. This was mostly to keep track of the breakage reported in https://github.com/JuliaSmoothOptimizers/NLPModels.jl/pull/236.

**Comment by abelsiqueira** [comment]
Thanks. I was gonna start that but I decided to push NLPModels first.

**Comment by dpo** [comment]
It seems I can't approve a PR that I opened myself ;-). But anyways, I approve of this!

**Pull request merged**
