### PR TITLE
Drop ampl/mp

### PR DESCRIPTION
**Pull request by dpo**

### CODE REVIEW

**Comment by dpo** [comment]
This resolves #52 and #13.

**Comment by dpo** [comment]
It seems ok, though the dreaded out-of-range indices showed up on Win 32bit: https://ci.appveyor.com/project/dpo/amplnlreader-jl/builds/19409121/job/j5fdijtv6v9xc8cj#L340.

Would you mind testing on Linux locally when you get a chance?

**Comment by abelsiqueira** [comment]
Thanks.

**Comment by dpo** [comment]
Great. Linux support is back and Windows 64bit as a bonus! It feels much lighter to not use ampl/mp.

**Pull request merged**
