### PR TITLE
Safe model

### PR DESCRIPTION
**Pull request by dpo**
This PR defines safe mode for an AMPL model.

I also removed the contribution of `lagscale` to constraint Hessians. The thinking is that if c(x) is a constraint function, its Hessian does not depend on a scaling parameter used in the definition of the Lagrangian.

### CODE REVIEW

**Comment by dpo** [comment]
I could call `obj(nlp, x)` and `cons(nlp, x)` instead of the `@asl_call`s. The initial thinking was that I didn't want to count the evaluations, but perhaps it doesn't matter in safe mode?!

**Comment by abelsiqueira** [comment]
I need write access, please.

**Comment by dpo** [comment]
I gave you write access and used simpler code.

**Comment by abelsiqueira** [comment]
Thank you.

**Pull request merged**
