### PR TITLE
require ForwardDiff for testing

### PR DESCRIPTION
**Pull request by dpo**
ForwardDiff is required by NLPModels

### CODE REVIEW

**Comment by abelsiqueira** [comment]
It should be installed as dependency from NLPModels.jl, no?

**Comment by abelsiqueira** [comment]
Or do you explictly need to use `ForwardDiff`?

**Comment by dpo** [comment]
For some reason, the tests fail under Julia 1.2.0-rc3 because ForwardDiff isn't present. I suspect something has changed where dependencies for tests must be stated explicitly.

**Comment by dpo** [comment]
This might need more investigation before merging.

**Comment by dpo** [comment]
Any idea about this? Here it is in action: https://travis-ci.org/JuliaSmoothOptimizers/AmplNLReader.jl/jobs/575127848#L562

**Comment by abelsiqueira** [comment]
Ok, here's the culprit: https://github.com/JuliaSmoothOptimizers/NLPModels.jl/blob/master/test/brownden.jl#L9
I guess we actually need `ForwardDiff` explicitly at the moment. Though I guess it would be better to compute the Hessian manually?

**Comment by dpo** [comment]
Right. The problem should disappear after https://github.com/JuliaSmoothOptimizers/NLPModels.jl/pull/200 but currently, it affects anything that relies on NLPModels's tests.

**Comment by abelsiqueira** [comment]
I'm working on the manual computation so this can be resolved

**Comment by abelsiqueira** [comment]
Done: https://github.com/JuliaSmoothOptimizers/NLPModels.jl/pull/203

**Comment by abelsiqueira** [comment]
https://github.com/JuliaRegistries/General/pull/2871

**Comment by dpo** [comment]
We should be able to close this as soon as #79 passes.

**Pull request closed without merging**
